### ISSUE TITLE
where is APL project?

### ISSUE THREAD

**Issue by hhhaiai** [shouldit/android-proxy-library-demo#1]
where is APL project?

this project can't work. losting library project

**Comment by hhhaiai** [comment]
where's  Android Proxy Library (APL)

**Comment by lechuckcaptain** [comment]
You can find everything in this project: 

https://github.com/shouldit/android-proxy

The Android Proxy Library (APL) is here: 

https://github.com/shouldit/android-proxy/tree/master/android-proxy-library
